import { Platform, PermissionsAndroid, Alert } from 'react-native';
import RNFS from 'react-native-fs';
import type { Task, Note } from '../types';

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function buildTasksHtml(tasks: Task[], title: string): string {
  const rows = tasks.map((t) => {
    const status = t.completed ? '✅' : '⬜';
    const due = t.dueDate ? new Date(t.dueDate).toLocaleDateString() : '—';
    const subs = t.subtasks.length > 0 ? t.subtasks.map((s) => `<li style="color:${s.completed ? '#999' : '#333'}">${s.completed ? '<s>' : ''}${escapeHtml(s.title)}${s.completed ? '</s>' : ''}</li>`).join('') : '';
    return `<tr>
      <td>${status}</td>
      <td><strong>${escapeHtml(t.title)}</strong>${subs ? `<ul style="margin:4px 0">${subs}</ul>` : ''}</td>
      <td>${due}</td>
      <td>${t.priority}</td>
    </tr>`;
  }).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body{font-family:sans-serif;padding:24px;color:#333}
    h1{color:#4A90D9;font-size:22px}
    table{width:100%;border-collapse:collapse;margin-top:16px}
    th,td{padding:8px 12px;border-bottom:1px solid #eee;text-align:left;font-size:13px}
    th{background:#f5f7fa;font-weight:600;color:#5a6578}
    ul{padding-left:16px;margin:0}
    li{font-size:12px}
    .footer{margin-top:24px;font-size:11px;color:#999}
  </style></head><body>
    <h1>${escapeHtml(title)}</h1>
    <p style="color:#888;font-size:12px">Exported on ${new Date().toLocaleDateString()}</p>
    <table>
      <tr><th></th><th>Task</th><th>Due Date</th><th>Priority</th></tr>
      ${rows}
    </table>
    <p class="footer">Generated by PlanUp</p>
  </body></html>`;
}

function buildNotesHtml(notes: Note[], title: string): string {
  const items = notes.map((n) => `
    <div style="margin-bottom:24px;padding:16px;border:1px solid #eee;border-radius:8px">
      <h2 style="font-size:16px;margin:0 0 8px">${escapeHtml(n.title || 'Untitled')}</h2>
      <div style="font-size:13px;color:#555">${n.content || '<em>No content</em>'}</div>
      <p style="font-size:11px;color:#999;margin-top:8px">${new Date(n.updatedAt).toLocaleDateString()}</p>
    </div>
  `).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body{font-family:sans-serif;padding:24px;color:#333}
    h1{color:#4A90D9;font-size:22px}
    .footer{margin-top:24px;font-size:11px;color:#999}
  </style></head><body>
    <h1>${escapeHtml(title)}</h1>
    <p style="color:#888;font-size:12px">Exported on ${new Date().toLocaleDateString()}</p>
    ${items}
    <p class="footer">Generated by PlanUp</p>
  </body></html>`;
}

async function ensurePermission(): Promise<boolean> {
  if (Platform.OS !== 'android') return false;
  try {
    const sdkInt = Platform.Version;
    if (typeof sdkInt === 'number' && sdkInt >= 30) return true; // Scoped storage
    const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);
    return granted === PermissionsAndroid.RESULTS.GRANTED;
  } catch { return false; }
}

export async function exportTasksToHtml(tasks: Task[], title: string = 'My Tasks'): Promise<string | null> {
  const ok = await ensurePermission();
  if (!ok && Number(Platform.Version) < 30) { Alert.alert('Permission denied'); return null; }
  try {
    const html = buildTasksHtml(tasks, title);
    const dir = RNFS.DownloadDirectoryPath;
    const fileName = `PlanUp_Tasks_${Date.now()}.html`;
    const path = `${dir}/${fileName}`;
    await RNFS.writeFile(path, html, 'utf8');
    Alert.alert('Exported!', `Saved to Downloads/${fileName}`);
    return path;
  } catch (e: any) {
    Alert.alert('Export failed', e?.message ?? 'Unknown error');
    return null;
  }
}

export async function exportNotesToHtml(notes: Note[], title: string = 'My Notes'): Promise<string | null> {
  const ok = await ensurePermission();
  if (!ok && Number(Platform.Version) < 30) { Alert.alert('Permission denied'); return null; }
  try {
    const html = buildNotesHtml(notes, title);
    const dir = RNFS.DownloadDirectoryPath;
    const fileName = `PlanUp_Notes_${Date.now()}.html`;
    const path = `${dir}/${fileName}`;
    await RNFS.writeFile(path, html, 'utf8');
    Alert.alert('Exported!', `Saved to Downloads/${fileName}`);
    return path;
  } catch (e: any) {
    Alert.alert('Export failed', e?.message ?? 'Unknown error');
    return null;
  }
}
